services:
  dynamodb-local:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - ./dynamodb:/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
  
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - dynamodb-local
    environment:
      - DYNAMODB_ENDPOINT=${DYNAMODB_ENDPOINT}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DYNAMODB_TABLE=${DYNAMODB_TABLE}